@baseUrl = http://localhost:3000
@accessToken =
@productId =
@articleId =
@otherProductId =
@otherArticleId =



> {% client.global.set("accessToken", response.body.accessToken) %}

### 1. 회원가입 성공
POST {{baseUrl}}/users/signup
Content-Type: application/json

{
  "email": "new@user.com",
  "nickname": "newbie",
  "password": "Passw0rd!"
}

### 2. 회원가입 중복 이메일 에러
POST {{baseUrl}}/users/signup
Content-Type: application/json

{ "email":"new@user.com","nickname":"dup","password":"xxx" }

### 3. 로그인 성공 (JWT 발급)
POST {{baseUrl}}/users/login
Content-Type: application/json

{ "email":"new@user.com","password":"Passw0rd!" }

> {% client.global.set("accessToken", response.body.accessToken) %}


###
### 4. 로그인 실패 (비밀번호 불일치)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "new@user.com",
  "password": "wrongpass"
}

###
### 5. 내 정보 조회 (유효 토큰)
GET {{baseUrl}}/users/me
Authorization: Bearer {{accessToken}}

###
### 6. 내 정보 조회 (토큰 없음)
GET {{baseUrl}}/users/me

###
### 7. 내 정보 수정 (유효 토큰)
PUT {{baseUrl}}/users/me
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "nickname": "updatedName"
}

###
### 8. 내 정보 삭제 (유효 토큰)
DELETE {{baseUrl}}/users/me
Authorization: Bearer {{accessToken}}

###
### 9. 상품 생성 (토큰 있음)
POST {{baseUrl}}/products
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Test Product",
  "price": 1000,
  "description": "desc"
}

> {% client.global.set("productId", response.body.id) %}

###
### 10. 상품 생성 (토큰 없음)
POST {{baseUrl}}/products
Content-Type: application/json

{
  "name": "X",
  "price": 0
}

###
### 11. 게시글 생성 (토큰 있음)
POST {{baseUrl}}/articles
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "Hello",
  "content": "World"
}

> {% client.global.set("articleId", response.body.id) %}

###
### 12. 댓글 생성 (상품, 토큰 있음)
POST {{baseUrl}}/products/{{productId}}/comments
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "content": "Nice!"
}

###
### 13. 댓글 생성 (게시글, 토큰 있음)
POST {{baseUrl}}/articles/{{articleId}}/comments
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "content": "Great post!"
}

###
### 14. 다른 유저가 올린 상품 수정 시도 → 권한 에러
PUT {{baseUrl}}/products/{{otherProductId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "price": 999
}

###
### 15. 다른 유저가 올린 게시글 삭제 시도 → 권한 에러
DELETE {{baseUrl}}/articles/{{otherArticleId}}
Authorization: Bearer {{accessToken}}
